name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        docker-compose -f local.yml run --rm django python -m pip install --upgrade pip
        docker-compose -f local.yml run --rm django python python -m pip install -r requirements/production.txt
    - name: Run Tests
      run: |
        docker-compose -f local.yml run --rm django python manage.py test
